version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fastapi-demo-sandbox"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bc1ko24lsdsx"
s3_prefix = "fastapi-demo-sandbox"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "env=\"sandbox\""
image_repositories = ["Function=853749126015.dkr.ecr.us-east-1.amazonaws.com/fastapidemosandbox6300c684/function86408593repo"]
