---
Transform: AWS::Serverless-2016-10-31
Description: fast api poetry ml demo
Parameters:
  env:
    Type: String
    Default: sandbox
    AllowedValues:
      - sandbox
      - qa
      - prod
    Description: deploy env

Resources:

  Api:
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html
    Type: AWS::Serverless::HttpApi

  Function:
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        !Sub fast-api-poetry-ml-${env}
      PackageType: Image
      MemorySize: 128
      Timeout: 90
      Role: !GetAtt FunctionRole.Arn
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .

  FunctionRole:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      MaxSessionDuration: 3600
      Path: /service-role/
      ManagedPolicyArns:
        - !Ref FunctiontManagedPolicy

  FunctiontManagedPolicy:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Path: /service-role/
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/fast-api-poetry-ml-${env}:*

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'
